// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

#include "weather.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace weather {
PROTOBUF_CONSTEXPR TemperatureResponse::TemperatureResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.temperature_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TemperatureResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TemperatureResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TemperatureResponseDefaultTypeInternal() {}
  union {
    TemperatureResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TemperatureResponseDefaultTypeInternal _TemperatureResponse_default_instance_;
}  // namespace weather
static ::_pb::Metadata file_level_metadata_weather_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_weather_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_weather_2eproto = nullptr;

const uint32_t TableStruct_weather_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::weather::TemperatureResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::weather::TemperatureResponse, _impl_.temperature_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::weather::TemperatureResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::weather::_TemperatureResponse_default_instance_._instance,
};

const char descriptor_table_protodef_weather_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rweather.proto\022\007weather\"*\n\023TemperatureR"
  "esponse\022\023\n\013temperature\030\001 \001(\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_weather_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_weather_2eproto = {
    false, false, 76, descriptor_table_protodef_weather_2eproto,
    "weather.proto",
    &descriptor_table_weather_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_weather_2eproto::offsets,
    file_level_metadata_weather_2eproto, file_level_enum_descriptors_weather_2eproto,
    file_level_service_descriptors_weather_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_weather_2eproto_getter() {
  return &descriptor_table_weather_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_weather_2eproto(&descriptor_table_weather_2eproto);
namespace weather {

// ===================================================================

class TemperatureResponse::_Internal {
 public:
};

TemperatureResponse::TemperatureResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:weather.TemperatureResponse)
}
TemperatureResponse::TemperatureResponse(const TemperatureResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TemperatureResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.temperature_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.temperature_ = from._impl_.temperature_;
  // @@protoc_insertion_point(copy_constructor:weather.TemperatureResponse)
}

inline void TemperatureResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.temperature_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TemperatureResponse::~TemperatureResponse() {
  // @@protoc_insertion_point(destructor:weather.TemperatureResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TemperatureResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TemperatureResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TemperatureResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:weather.TemperatureResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.temperature_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TemperatureResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float temperature = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.temperature_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TemperatureResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:weather.TemperatureResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float temperature = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = this->_internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_temperature(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:weather.TemperatureResponse)
  return target;
}

size_t TemperatureResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:weather.TemperatureResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float temperature = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = this->_internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TemperatureResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TemperatureResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TemperatureResponse::GetClassData() const { return &_class_data_; }


void TemperatureResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TemperatureResponse*>(&to_msg);
  auto& from = static_cast<const TemperatureResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:weather.TemperatureResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_temperature = from._internal_temperature();
  uint32_t raw_temperature;
  memcpy(&raw_temperature, &tmp_temperature, sizeof(tmp_temperature));
  if (raw_temperature != 0) {
    _this->_internal_set_temperature(from._internal_temperature());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TemperatureResponse::CopyFrom(const TemperatureResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:weather.TemperatureResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TemperatureResponse::IsInitialized() const {
  return true;
}

void TemperatureResponse::InternalSwap(TemperatureResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.temperature_, other->_impl_.temperature_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TemperatureResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_weather_2eproto_getter, &descriptor_table_weather_2eproto_once,
      file_level_metadata_weather_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace weather
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::weather::TemperatureResponse*
Arena::CreateMaybeMessage< ::weather::TemperatureResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::weather::TemperatureResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
